In [1]:
import experiment_generation as EG
import channels as Ch
import numpy as N

In [2]:
%matplotlib inline
%pylab
import matplotlib as mpl

Using matplotlib backend: Qt5Agg
Populating the interactive namespace from numpy and matplotlib


In [3]:
mpl.rcParams['axes.grid'] = True

mpl.rcParams['grid.linestyle'] = 'dotted'

mpl.rcParams['font.size'] = 12

mpl.rcParams['figure.titlesize'] = 16

In [4]:
tolcolors_med_contrast={
'ly': '#EECC66',
'lr': '#EE99AA',
'lb': '#6699CC',
'dy': '#997700',
'dr': '#994455',
'db': '#004488',    
}
custom_cycler = (cycler(color=[tolcolors_med_contrast[ss] for ss in ['db', 'dy', 'lr', 'lb', 'ly', 'dr']]))

In [8]:
spec_custom_cycler = (cycler(color=[tolcolors_med_contrast[ss] for ss in ['lr', 'db', 'lb', 'dy', 'ly']]))

fig, axes = subplots(dpi=300)
axes.set_prop_cycle(spec_custom_cycler)
#for proj in ['HIPswitch','Dykstra','Alternate','pureHIP','oneHIP']:
for proj in ['oneHIP', 'HIPswitch', 'pureHIP', 'Dykstra','Alternate']:
        ex = EG.retrieve_main(f'article_experiments/compare_QFT_1e7.h5', proj_type=proj)
        if proj=='Alternate':
            proj='AP'
        plot(np.log10(-ex['least_ev']), label=proj)#, linewidth=1)


axes.set_ylabel("$\log_{10}(-\lambda_{min})$", fontsize='large')

axes.set_xlabel("Iteration", fontsize='large')

axes.legend()


In [295]:
fig, axes = subplots()
axes.set_prop_cycle(custom_cycler)
#for proj in ['HIPswitch','Dykstra','Alternate','pureHIP','oneHIP']:
for proj in ['oneHIP', 'HIPswitch', 'pureHIP', 'Dykstra','Alternate']:
        ex = EG.retrieve_main(f'article_experiments/compare_QFT_1e7.h5', proj_type=proj)
        plot(np.log10((ex['dist_L2'][1:-1]-0.0437333225952)), label=proj)#, linewidth=1)


In [11]:
fig, ax = subplots(dpi=300)
ax.set_prop_cycle(custom_cycler)

x = np.linspace(2e5, 1.2e8)

ss=[]
L1LS = []
L1f = []
for n in ['3e5', '1e6', '3e6', '1e7', '3e7', '1e8']:
#for n in ['3e5']: 
    for i in range(10):
        ex = EG.retrieve_main(f'article_experiments/sample_size_QFT_{n}.h5', exp_number=i)
        ss.append(ex['sample_size'])
        L1LS.append(ex['dist_L1'][0])
        L1f.append(ex['dist_L1'][-1])


loglog(x, ex['dist_L1'][0] / np.sqrt(x / 1e8), color=tolcolors_med_contrast['ly'])
loglog(x, 3 * ex['dist_L1'][0] / (np.sqrt(x / 1e8) * 4**5), color=tolcolors_med_contrast['lb'])
loglog(x, 4.5 * ex['dist_L1'][0] / (np.sqrt(x / 1e8) * 4**5), color=tolcolors_med_contrast['lb'])
        
        
sc1 = scatter(ss, L1LS, color=tolcolors_med_contrast['dy'], s=2, label='LS estimator', zorder=2.5)
sc2 = scatter(ss, L1f, color=tolcolors_med_contrast['db'], s=2, label='Final estimator', zorder=2.5)
        #scatter(ex['sample_size'], ex['dist_L1'][1], color='b')

ax.set_ylabel("Trace norm loss", fontsize='large', x=8)
ax.yaxis.set_label_coords(-.1, .5)

ax.set_xlabel("Sample size", fontsize='large')
ax.xaxis.set_label_coords(.5, -.12)
subplots_adjust(bottom=.15)

ax.legend(scatteryoffsets=(.5,.5), markerscale=5)#, *sc2.legend_elements(prop="sizes"))

In [12]:
x = np.linspace(2e5, 1.2e8)
plot(x, y8 / np.sqrt(x / 1e8))

In [13]:
plot(x, ex['dist_L1'][0] / np.sqrt(x / 1e8))

In [12]:
fig, ax1 = subplots(dpi=150, figsize=(6, 4))
rank = []
L1t = []
L1f = []
L1tmin = [0]
for f in ['1', '2', '4', '8', '16', '32']:
    for i in range(10):
        rank.append(int(f))
        ex = EG.retrieve_main(f'article_experiments/rank_equal{f}.h5', exp_number=i)
        L1t.append(ex['dist_L1'][-1])
        ex = EG.retrieve_main(f'article_experiments/rank_equal{f}_1e6_False.h5', exp_number=i)
        L1f.append(ex['dist_L1'][-1])      
    L1tmin.append(N.min(L1t[-10:]))
scatter(rank, L1t, color=tolcolors_med_contrast['db'], s=10, label="$10^6$")
scatter(rank, L1f, color=tolcolors_med_contrast['lb'], s=10, label="$10^6$, no thres")
plot([0, 1, 2, 4, 8, 16, 32], L1tmin, color=tolcolors_med_contrast['db'])


rank = []
L1t = []
L1f = []
L1tmin = [0]
for f in ['1', '2', '4', '8', '16', '32']:
    for i in range(10):
        rank.append(int(f))
        ex = EG.retrieve_main(f'article_experiments/rank_equal{f}_1e8.h5', exp_number=i)
        L1t.append(ex['dist_L1'][-1])
        ex = EG.retrieve_main(f'article_experiments/rank_equal{f}_1e8_False.h5', exp_number=i)
        L1f.append(ex['dist_L1'][-1])    
    L1tmin.append(N.min(L1t[-10:]))
scatter(rank, L1t, color=tolcolors_med_contrast['dr'], s=10, label="$10^8$")
scatter(rank, L1f, color=tolcolors_med_contrast['lr'], s=10, label="$10^8$, no thres")
plot([0, 1, 2, 4, 8, 16, 32], L1tmin, color=tolcolors_med_contrast['dr'])


rank = []
L1t = []
L1f = []
L1tmin = [0]
for f in ['1', '2', '4', '8', '16', '32']:
    for i in range(10):
        rank.append(int(f))
        ex = EG.retrieve_main(f'article_experiments/rank_equal{f}_1e7.h5', exp_number=i)
        L1t.append(ex['dist_L1'][-1])
        ex = EG.retrieve_main(f'article_experiments/rank_equal{f}_1e7_False.h5', exp_number=i)
        L1f.append(ex['dist_L1'][-1])    
    L1tmin.append(N.min(L1t[-10:]))

scatter(rank, L1t, color=tolcolors_med_contrast['dy'], s=10, label="$10^7$")
scatter(rank, L1f, color=tolcolors_med_contrast['ly'], s=10, label="$10^7$, no thres")
plot([0, 1, 2, 4, 8, 16, 32], L1tmin, color=tolcolors_med_contrast['dy'])


#ax1.set_ylim(0.025, 2.1)
ax1.set_ylim(0, 2)
#ax1.set_xscale('log')
#ax1.set_yscale('log')

ax1.set_xlim(0)
#ax1.set_xticks([], minor=True)
#ax1.set_xticks([1, 2, 4, 8, 16, 32])
#ax1.set_xticklabels([1, 2, 4, 8, 16, 32])

#ax1.set_yticks([], minor=True)
#yl = [.025, .05, .1, .25, .5,  1, 1.5, 2]
#ax1.set_yticks(yl)
#ax1.set_yticklabels(yl)

ax1.set_ylabel("Trace norm loss", fontsize='large')

ax1.set_xlabel("Rank", fontsize='large')

subplots_adjust(left=.15)

ax1.legend(title="Samples", loc='lower right', bbox_to_anchor=(1, -.05), scatteryoffsets=(.5,.5), markerscale=2)

In [449]:
ax1.legend(title="Samples", loc='lower right', bbox_to_anchor=(1, -.05), scatteryoffsets=(.5,.5), markerscale=2)
subplots_adjust(left=.15)

In [388]:
ax1.set_ylim(0.02, 2.1)

yl = [.02, .03, .1,  .3,  1,  2]
ax1.set_yticks(yl)
ax1.set_yticklabels(yl)

[Text(0, 0.02, '0.02'),
 Text(0, 0.03, '0.03'),
 Text(0, 0.1, '0.1'),
 Text(0, 0.3, '0.3'),
 Text(0, 1.0, '1'),
 Text(0, 2.0, '2')]

In [416]:
EG.retrieve_main(f'article_experiments/rank_equal1_1e8.h5', exp_number=0)

{'sample_size': 99995175,
 'time_proj': 12.081388040678576,
 'dist_L2': array([0.31209347, 0.01827147, 0.01826293, 0.0182585 , 0.01825414,
        0.01824971, 0.01824537, 0.01824094, 0.01534803, 0.01533054,
        0.01532989, 0.0153297 , 0.01530783, 0.01529821, 0.01529807,
        0.01529799, 0.01529792, 0.01529784, 0.01529777, 0.01529769,
        0.01529762, 0.01529754, 0.01529747, 0.0152974 , 0.01527994,
        0.01527376, 0.01526689, 0.01526661, 0.01526642, 0.01526637,
        0.01526587, 0.01526581, 0.01526556, 0.01526552, 0.01526491,
        0.01526485, 0.01526476, 0.01526474, 0.01526372, 0.01526352,
        0.01526351, 0.0152635 , 0.01526351, 0.01565856]),
 'dist_L1': array([8.4396913 , 0.02583976, 0.02691893, 0.02749777]),
 'dist_Linfty': array([0.01987705, 0.01291988, 0.01306717, 0.01374889]),
 'least_ev': array([-1.98092099e-02, -3.33840858e-05, -3.33177707e-05, -3.32574747e-05,
        -7.01716737e-04, -6.42064241e-06, -4.81305024e-04, -5.20812602e-06,
        -3.18734002e-

In [402]:
EG.retrieve_main?

In [30]:
figure()
for i in range(10):
    for f in ['1', '2', '4', '8', '16', '32']:
        ex = EG.retrieve_main(f'article_experiments/rank_equal{f}_1e8.h5', exp_number=i)
        scatter(int(f),  ex['dist_L1'][-1], color='C0')
        #scatter(int(f),  ex['dist_L1'][1])
        exF = EG.retrieve_main(f'article_experiments/rank_equal{f}_1e8_False.h5', exp_number=i)
        scatter(int(f),  exF['dist_L1'][-1], color='C1')
        #scatter(int(f),  ex['dist_L1'][1])  

/home/jokahn/.science/lib/python3.8/site-packages/ipykernel/eventloops.py:105: UserWarning: Attempted to set non-positive bottom ylim on a log-scaled axis.
Invalid limit will be ignored.
  app.exec_()


In [46]:
figure()
for i in range(10):
    for f in ['1', '2', '4', '8', '16']:
        ex = EG.retrieve_main(f'article_experiments/rank_geom{f}.h5', exp_number=i)
        scatter(int(f),  ex['dist_L1'][-1], color='C0')
        #scatter(int(f),  ex['dist_L1'][1])
        exF = EG.retrieve_main(f'article_experiments/rank_geom{f}_1e6_False.h5', exp_number=i)
        scatter(int(f),  exF['dist_L1'][-1], color='C1')
        #scatter(int(f),  ex['dist_L1'][1])  

In [59]:
def est_manq(evs, seuil):
    return 2 * N.clip(evs, a_min=None, a_max=seuil).sum()

In [60]:
N.clip?

In [61]:
def geomevs(dim, mult, rank=32):
    weights_unnormalized = mult**np.arange(rank)
    weights = weights_unnormalized / (weights_unnormalized).sum()
    return weights

In [65]:

[est_manq(geomevs(4**5, 4**(1/i)), .1) for i in [.25, .5, 1, 2, 4, 8, 16]]

[0.2078125,
 0.325,
 0.525,
 0.8499999995925465,
 1.2999771114671548,
 1.7860275350615555,
 1.9999999999999998]

In [66]:

[est_manq(geomevs(4**5, 4**(1/i)), .3) for i in [.25, .5, 1, 2, 4, 8, 16]]

[0.6078125,
 0.725,
 1.0999999999999999,
 1.5999999997671694,
 2.0,
 2.0,
 1.9999999999999998]

In [68]:
import scipy.stats as SS
SS.hmean(geomevs(2**5, 4))

3.903127820947817e-18

In [34]:
figure()
for i in range(10):
    for d in [3, 7, 11, 17, 31, 67]:
        ex = EG.retrieve_main(f'article_experiments/dimension_{d}_MUBs.h5', exp_number=i)
        scatter(d,  ex['dist_L1'][-1], color='C0')

/home/jokahn/.science/lib/python3.8/site-packages/ipykernel/eventloops.py:105: UserWarning: Attempted to set non-positive left xlim on a log-scaled axis.
Invalid limit will be ignored.
  app.exec_()


In [ ]:
for i in range(9):
    for d in [3, 7, 11, 17, 31, 67]:
        ex = EG.retrieve_main(f'article_experiments/dimension_{d}_MUBs.h5', exp_number=i)
        scatter(d,  ex['dist_L1'][-1], color='C0')

In [37]:
for k in range(1, 7):
    ex = EG.retrieve_main(f'article_experiments/dimension_{k}_qubits.h5', exp_number=0)
    scatter(2**k,  ex['dist_L1'][-1], color='C1')   
    for i in range(9):
        ex = EG.retrieve_main(f'article_experiments/dimension_{k}_qubits_bis.h5', exp_number=i)
        scatter(2**k,  ex['dist_L1'][-1], color='C1')          

In [18]:
L = {}
for d in [3, 7, 11, 17, 31, 67]:
    L[d] = []
    for i in range(10):
        ex = EG.retrieve_main(f'article_experiments/dimension_{d}_MUBs.h5', exp_number=i)
        L[d].append(ex['dist_L1'][-1])  

In [19]:
MUBs_loss = [(key, mean(value)) for key, value in L.items()]
    

In [17]:
P = {}
for k in range(1, 7):
    ex = EG.retrieve_main(f'article_experiments/dimension_{k}_qubits.h5', exp_number=0)
    P[2**k] = [ex['dist_L1'][-1]]  
    for i in range(9):
        ex = EG.retrieve_main(f'article_experiments/dimension_{k}_qubits_bis.h5', exp_number=i)
        P[2**k].append(ex['dist_L1'][-1])
Pauli_loss = [(key, mean(value)) for key, value in P.items()]

In [92]:
fig, (ax1, ax2) = subplots(ncols=2, sharex=True)
ax1.plot([xy[0] for xy in  Pauli_loss], [xy[1] for xy in Pauli_loss], label='Pauli')
ax1.plot([xy[0] for xy in  MUBs_loss], [xy[1] for xy in MUBs_loss],label='MUBs')

ax1.set_xscale('log')

ax1.set_xticks([], minor=True)
ax1.set_xticks([2, 4, 8, 16, 32, 64])
ax1.set_xticklabels([2, 4, 8, 16, 32, 64])


ax1.set_ylim(0, 0.6)

ax1.set_ylabel("$L^1$ loss", fontsize='large')

ax1.set_xlabel("Dimension", fontsize='large')

ax1.legend()

In [85]:
fig.set_constrained_layout?

In [88]:
GridSpec(1, 2, figure=fig)

GridSpec(1, 2)

In [90]:
ax1.set_box_aspect(.5)

In [91]:
ax1.set_xticks([2, 4, 8, 16, 32, 64])


In [93]:
#for d in [3, 7, 11, 17, 31, 67]:
        d=3
        ex = EG.tables.open_file(f'article_experiments/dimension_{d}_MUBs.h5','r')
    

IndentationError: unexpected indent (<ipython-input-93-c1aaac63f059>, line 2)

In [102]:
d=67
ex = EG.tables.open_file(f'article_experiments/dimension_{d}_MUBs.h5','r')
    

In [103]:
ex.root.exp_repet0.projection_HIPswitch.loops.attrs.computation_time

4063.265250538825

In [104]:
len(ex.root.exp_repet0.projection_HIPswitch.loops)

159

In [106]:
ex.root.exp_repet0.projection_HIPswitch.loops.cols.CP_proj_time[10]

21.546469032997265

In [107]:
4063 / 159

25.553459119496857

In [15]:
MUBs_time_per_loop = []
MUBs_total_comp_time = []
for d in [3, 7, 11, 17, 31, 67]:
    ex = EG.tables.open_file(f'article_experiments/dimension_{d}_MUBs.h5','r')
    comp_time = 0
    nloops = 0
    dgt = 0
    for i in range(10):
        comp_time += eval(f'ex.root.exp_repet{i}.projection_HIPswitch.loops.attrs.computation_time')
        nloops += eval(f'len(ex.root.exp_repet{i}.projection_HIPswitch.loops)')   
        dgt += eval(f'ex.root.exp_repet{i}.initialisation.cols.data_generation_and_LS_time[:]')
    MUBs_total_comp_time.append((d, (ex.root.summary.attrs.total_computation_time - dgt) / 10))
    MUBs_time_per_loop.append((d, comp_time / nloops))

In [71]:
MUBs_time_per_loop, MUBs_total_comp_time

([(3, 0.0005160547109281129),
  (7, 0.0024995891344588017),
  (11, 0.007848404878533857),
  (17, 0.04031915378900582),
  (31, 0.38843643754892737),
  (67, 25.422260774910477)],
 [(3, array([0.00270929])),
  (7, array([0.03351816])),
  (11, array([0.14528062])),
  (17, array([1.25374907])),
  (31, array([19.73730766])),
  (67, array([3953.88303335]))])

In [14]:
Pauli_time_per_loop = []
Pauli_total_comp_time = []
for k in range(1, 7):
    ex = EG.tables.open_file(f'article_experiments/dimension_{k}_qubits.h5','r')
    comp_time = eval(f'ex.root.exp_repet0.projection_HIPswitch.loops.attrs.computation_time')
    nloops = eval(f'len(ex.root.exp_repet0.projection_HIPswitch.loops)')  
    dgt = eval(f'ex.root.exp_repet0.initialisation.cols.data_generation_and_LS_time[:]')
    tct = ex.root.summary.attrs.total_computation_time
    ex = EG.tables.open_file(f'article_experiments/dimension_{k}_qubits_bis.h5','r')    
    for i in range(9):
        comp_time += eval(f'ex.root.exp_repet{i}.projection_HIPswitch.loops.attrs.computation_time')
        nloops += eval(f'len(ex.root.exp_repet{i}.projection_HIPswitch.loops)')   
        dgt += eval(f'ex.root.exp_repet{i}.initialisation.cols.data_generation_and_LS_time[:]')
    tct += ex.root.summary.attrs.total_computation_time
    Pauli_total_comp_time.append((2**k, (tct - dgt) / 10))
    Pauli_time_per_loop.append((2**k, comp_time / nloops))

In [73]:
Pauli_time_per_loop, Pauli_total_comp_time

([(2, 0.000468661606178752),
  (4, 0.0005765369525021416),
  (8, 0.00408351829040353),
  (16, 0.034584175727876094),
  (32, 0.5468318413540746),
  (64, 22.146089105880534)],
 [(2, array([0.00191954])),
  (4, array([0.00372088])),
  (8, array([0.04348036])),
  (16, array([0.53011263])),
  (32, array([16.5886676])),
  (64, array([1475.80982673]))])

In [126]:
22.14 / 0.546, 1475 / 16.59

(40.54945054945055, 88.90898131404461)

In [20]:
fig, (ax1, ax2) = subplots(nrows=2, sharex=True, figsize=[6, 9])
ax1.plot([xy[0] for xy in  Pauli_loss], [xy[1] for xy in Pauli_loss], label='Pauli', color=tolcolors_med_contrast['db'])
ax1.plot([xy[0] for xy in  MUBs_loss], [xy[1] for xy in MUBs_loss],label='MUBs', color=tolcolors_med_contrast['dy'])

ax1.set_xscale('log')

ax1.set_xticks([], minor=True)
ax1.set_xticks([2, 4, 8, 16, 32, 64])
ax1.set_xticklabels([2, 4, 8, 16, 32, 64])


ax1.set_ylim(0, 0.6)

ax1.set_ylabel("Trace norm loss", fontsize='large')

#ax1.set_xlabel("Dimension", fontsize='large')
#ax2.set_xlabel("Dimension", fontsize='large')

ax1.legend()

ax2.plot([xy[0] for xy in  Pauli_time_per_loop], [xy[1] for xy in Pauli_time_per_loop], label='Pauli time per loop',
        color=tolcolors_med_contrast['lb'])
ax2.plot([xy[0] for xy in  MUBs_time_per_loop], [xy[1] for xy in MUBs_time_per_loop], label='MUBs time per loop',
        color=tolcolors_med_contrast['ly'])
ax2.plot([xy[0] for xy in  Pauli_total_comp_time], [xy[1] for xy in Pauli_total_comp_time], label='Pauli total time after LS',
        color=tolcolors_med_contrast['db'])
ax2.plot([xy[0] for xy in  MUBs_total_comp_time], [xy[1] for xy in MUBs_total_comp_time], label='MUBs total time after LS',
        color=tolcolors_med_contrast['dy'])

ax2.set_yscale('log')
ax2.set_ylabel("Time (s)", fontsize='large')
ax2.yaxis.set_label_coords(-.1, .55)
ax2.legend()

#subplots_adjust(wspace=.3, right=.95, left=.1)
#fig.suptitle("Effect of dimension", fontsize=16)
fig.supxlabel("Dimension", fontsize='large', x=.5, y=.05)

Text(0.5, 0.05, 'Dimension')

In [125]:
subplots_adjust(bottom=.1, top=.95)
fig.supxlabel("Dimension", fontsize='large', x=.51, y=.03)


Text(0.51, 0.03, 'Dimension')

In [213]:
ax2.grid(linestyle='dotted')

In [241]:
subplots_adjust(wspace=.3, right=.95)

In [234]:
fig.suptitle("Effect of dimension", fontsize=16)

Text(0.5, 0.98, 'Effect of dimension')

In [249]:
fig.supxlabel?

In [5]:
t12 = EG.tables.open_file('clean_progs/Jonas_experiment_7_qubits/vignette_7_qubits_1e12.h5', 'r')

In [6]:
t12.root.summary[:]

array([(0.00392976, 0.00180629, 0.00101214, 0.00452471, 0.00174432, 0.00104797, 0.00536477, 0.00212528, 0.00161432, -1., 6, 8.4649111, 0.07812167, 0.00123978, 999999154116, 58005.67123074)],
      dtype=[('CP_dist_L1', '<f8'), ('CP_dist_L2', '<f8'), ('CP_dist_Linfty', '<f8'), ('HIPswitch_TPfinal_dist_L1', '<f8'), ('HIPswitch_TPfinal_dist_L2', '<f8'), ('HIPswitch_TPfinal_dist_Linfty', '<f8'), ('HIPswitch_final_dist_L1', '<f8'), ('HIPswitch_final_dist_L2', '<f8'), ('HIPswitch_final_dist_Linfty', '<f8'), ('HIPswitch_max_active_w', '<f8'), ('HIPswitch_number_of_iterations', '<i8'), ('LS_dist_L1', '<f8'), ('LS_dist_L2', '<f8'), ('LS_dist_Linfty', '<f8'), ('sample_size', '<i8'), ('time_exp', '<f8')])

In [7]:
t12.root.exp_repet0.projection_HIPswitch.end[:]

array([(-1., 0., 0.00452471, 0.00174432, 0.00104797, 0.99897247, -5.22305724e-08, 0.00536477, 0.00212528, 0.00161432, 0.99811646, 117.8123805, -1)],
      dtype=[('total_time', '<f8'), ('TP_proj_time', '<f8'), ('TPfinal_dist_L1', '<f8'), ('TPfinal_dist_L2', '<f8'), ('TPfinal_dist_Linfty', '<f8'), ('TPfinal_fidelity', '<f8'), ('TPfinal_least_ev', '<f8'), ('final_dist_L1', '<f8'), ('final_dist_L2', '<f8'), ('final_dist_Linfty', '<f8'), ('final_fidelity', '<f8'), ('final_proj_time', '<f8'), ('number_of_iterations', '<i8')])

In [10]:
t8 = EG.tables.open_file('clean_progs/Jonas_experiment_7_qubits/vignette_7_qubits_1e8.h5', 'r')

In [11]:
t8.root.exp_repet0.projection_HIPswitch.end[:]

array([(-1., 0., 0.39229653, 0.16080858, 0.11744183, 0.84401786, -2.5263132e-07, 0.39649712, 0.16223648, 0.11978076, 0.84053928, 654.10074586, -1)],
      dtype=[('total_time', '<f8'), ('TP_proj_time', '<f8'), ('TPfinal_dist_L1', '<f8'), ('TPfinal_dist_L2', '<f8'), ('TPfinal_dist_Linfty', '<f8'), ('TPfinal_fidelity', '<f8'), ('TPfinal_least_ev', '<f8'), ('final_dist_L1', '<f8'), ('final_dist_L2', '<f8'), ('final_dist_Linfty', '<f8'), ('final_fidelity', '<f8'), ('final_proj_time', '<f8'), ('number_of_iterations', '<i4')])

In [13]:
t8.root.summary[:]

array([(0.37848834, 0.1664338, 0.11436093, 0.39229653, 0.16080858, 0.11744183, 0.39649712, 0.16223648, 0.11978076, -1., 179, 846.4937221, 7.8121137, 0.12378013, -221636664, 277588.65913234)],
      dtype=[('CP_dist_L1', '<f8'), ('CP_dist_L2', '<f8'), ('CP_dist_Linfty', '<f8'), ('HIPswitch_TPfinal_dist_L1', '<f8'), ('HIPswitch_TPfinal_dist_L2', '<f8'), ('HIPswitch_TPfinal_dist_Linfty', '<f8'), ('HIPswitch_final_dist_L1', '<f8'), ('HIPswitch_final_dist_L2', '<f8'), ('HIPswitch_final_dist_Linfty', '<f8'), ('HIPswitch_max_active_w', '<f8'), ('HIPswitch_number_of_iterations', '<i4'), ('LS_dist_L1', '<f8'), ('LS_dist_L2', '<f8'), ('LS_dist_Linfty', '<f8'), ('sample_size', '<i4'), ('time_exp', '<f8')])

In [12]:
figure()
plot(N.log10(-t8.root.exp_repet0.projection_HIPswitch.loops.cols.TP_least_ev[:]))

In [30]:
t10 = EG.tables.open_file('clean_progs/Jonas_experiment_7_qubits/vignette_7_qubits_1e10.h5', 'r')

In [31]:
t10.root.summary[:]

array([(0.04449982, 0.01930924, 0.01148048, 0.04899487, 0.01884029, 0.01190757, 0.05317144, 0.02086858, 0.01492901, -1., 41, 84.65478429, 0.78126149, 0.01238586, -511228928, 91005.91143666)],
      dtype=[('CP_dist_L1', '<f8'), ('CP_dist_L2', '<f8'), ('CP_dist_Linfty', '<f8'), ('HIPswitch_TPfinal_dist_L1', '<f8'), ('HIPswitch_TPfinal_dist_L2', '<f8'), ('HIPswitch_TPfinal_dist_Linfty', '<f8'), ('HIPswitch_final_dist_L1', '<f8'), ('HIPswitch_final_dist_L2', '<f8'), ('HIPswitch_final_dist_Linfty', '<f8'), ('HIPswitch_max_active_w', '<f8'), ('HIPswitch_number_of_iterations', '<i4'), ('LS_dist_L1', '<f8'), ('LS_dist_L2', '<f8'), ('LS_dist_Linfty', '<f8'), ('sample_size', '<i4'), ('time_exp', '<f8')])

In [36]:
figure(dpi=300)
imshow(t8.root.exp_repet0.projection_HIPswitch.main_eigvecs_final[:,0].real.reshape(128, 128))

In [44]:
#figure(dpi=300)
matshow(t8.root.exp_repet0.projection_HIPswitch.main_eigvecs_final[:,1].real.reshape(128, 128))

In [38]:
figure(dpi=300)
imshow(t8.root.exp_repet0.projection_HIPswitch.main_eigvecs_final[:,0].imag.reshape(128, 128))

In [ ]:
N.ar(1+1j)

In [49]:
import cmath

In [51]:
cmath.polar?

In [61]:
import cmath
def align(ref_vec, test_vec):
    phi = cmath.phase(N.vdot(ref_vec, test_vec))
    return test_vec * exp(- phi * 1j)

In [25]:
v1, v2 = {}, {}
for t in [t7, t8, t9, t10, t12]:
    v1[t] = align(t.root.main_eigvecs_true[:,1], t.root.exp_repet0.projection_HIPswitch.main_eigvecs_final[:,1]).reshape(128, 128)    
    v2[t] = align(t.root.main_eigvecs_true[:,0], t.root.exp_repet0.projection_HIPswitch.main_eigvecs_final[:,0]).reshape(128, 128)

In [65]:
matshow(v1[t12].real)

In [7]:
for item, value in v1:
    print(item)

NameError: name 'v1' is not defined

In [79]:
figure(dpi=256)
imshow(t7.root.main_eigvecs_true[:,1].real.reshape(128, 128))
grid(False)

In [83]:
figure(dpi=256)
imshow(t7.root.main_eigvecs_true[:,1].real.reshape(128, 128), cmap='ocean')
grid(False)

In [75]:
figure(dpi=256)
imshow(v1[t7].real)
grid(False)

In [76]:
figure(dpi=256)
imshow(v1[t10].real)
grid(False)

In [77]:
figure(dpi=256)
imshow(v1[t9].real)
grid(False)

In [78]:
colorbar()

In [71]:
grid(False)

In [39]:
c6 = EG.tables.open_file('experiments/compare_6qubits.h5', 'r')

In [42]:
c5 = EG.tables.open_file('article_experiments/compare_QFT_1e7.h5', 'r')

In [43]:
c5.root.summary[:]

array([(0.0986942, 0.04712444, 0.03583673, 0.1398892, 0.07154836, 0.0699446, -1., 299, 0.07361587, 0.05205428, 0.03680793, 0.09875558, 0.0471432, 0.0358511, 0.140242, 0.07171501, 0.070121, -1., 299, 0.07502404, 0.04373332, 0.03751202, 0.07502404, 0.04373332, 0.03751202, -1., 299, 26.80451805, 0.98908355, 0.06207687, 0.07619414, 0.0437727, 0.03715987, 0.07930504, 0.04515809, 0.03965252, -1., 299, 0.07538241, 0.04380948, 0.03769117, 0.07538462, 0.0438101, 0.03769231, -1., 299, 10002249, 1118.49784633)],
      dtype=[('Alternate_TPfinal_dist_L1', '<f8'), ('Alternate_TPfinal_dist_L2', '<f8'), ('Alternate_TPfinal_dist_Linfty', '<f8'), ('Alternate_final_dist_L1', '<f8'), ('Alternate_final_dist_L2', '<f8'), ('Alternate_final_dist_Linfty', '<f8'), ('Alternate_max_active_w', '<f8'), ('Alternate_number_of_iterations', '<i4'), ('CP_dist_L1', '<f8'), ('CP_dist_L2', '<f8'), ('CP_dist_Linfty', '<f8'), ('Dykstra_TPfinal_dist_L1', '<f8'), ('Dykstra_TPfinal_dist_L2', '<f8'), ('Dykstra_TPfinal_dist_Linf

In [ ]:
0.0986 0.073 0.0987 0.075 0.075 0.079

In [44]:
c18 = EG.tables.open_file('experiments/test18.h5', 'r')

In [45]:
c18.root.summary[:]

array([(0.14723503, 0.07855978, 0.0699193, 0.1601621, 0.08691869, 0.08008105, 199, 0.13607234, 0.08358684, 0.06803617, 0.14760621, 0.07845311, 0.06992903, 0.16204509, 0.08763525, 0.08102255, 199, 0.14335215, 0.07878088, 0.07167398, 0.14347366, 0.07883265, 0.07173683, 82, 0.14169163, 0.0785611, 0.07068807, 0.14345558, 0.07940256, 0.07172779, 199, 8.29136555, 0.61110533, 0.07634066, 1049435, 26.39100922)],
      dtype=[('Alternate_TPfinal_dist_L1', '<f8'), ('Alternate_TPfinal_dist_L2', '<f8'), ('Alternate_TPfinal_dist_Linfty', '<f8'), ('Alternate_final_dist_L1', '<f8'), ('Alternate_final_dist_L2', '<f8'), ('Alternate_final_dist_Linfty', '<f8'), ('Alternate_number_of_iterations', '<i4'), ('CP_dist_L1', '<f8'), ('CP_dist_L2', '<f8'), ('CP_dist_Linfty', '<f8'), ('Dykstra_TPfinal_dist_L1', '<f8'), ('Dykstra_TPfinal_dist_L2', '<f8'), ('Dykstra_TPfinal_dist_Linfty', '<f8'), ('Dykstra_final_dist_L1', '<f8'), ('Dykstra_final_dist_L2', '<f8'), ('Dykstra_final_dist_Linfty', '<f8'), ('Dykstra_numbe

In [5]:
t7 = EG.tables.open_file('clean_progs/Jonas_experiment_7_qubits/vignette_7_qubits_1e7.h5', 'r')
t8 = EG.tables.open_file('clean_progs/Jonas_experiment_7_qubits/vignette_7_qubits_1e8.h5', 'r')
t9 = EG.tables.open_file('clean_progs/Jonas_experiment_7_qubits/vignette_7_qubits_1e9.h5', 'r')
t10 = EG.tables.open_file('clean_progs/Jonas_experiment_7_qubits/vignette_7_qubits_1e10.h5', 'r')
t12 = EG.tables.open_file('clean_progs/Jonas_experiment_7_qubits/vignette_7_qubits_1e12.h5', 'r')


In [6]:
H7 = t7.root.exp_repet0.projection_HIPswitch
H8 = t8.root.exp_repet0.projection_HIPswitch
H9 = t9.root.exp_repet0.projection_HIPswitch
H10 = t10.root.exp_repet0.projection_HIPswitch
H12 = t12.root.exp_repet0.projection_HIPswitch

In [42]:
figure(dpi=300)
matshow(t7.root.exp_repet0.projection_HIPswitch.main_eigvecs_final[:,0].real.reshape(128, 128))

In [23]:
figure(dpi=50)
imshow(t7.root.exp_repet0.projection_HIPswitch.main_eigvecs_final[:,1].real.reshape(128, 128)[:64, :64])

In [37]:
figure(dpi=300)
imshow(t12.root.exp_repet0.projection_HIPswitch.main_eigvecs_final[:,1].real.reshape(128, 128)[32:96, 32:96]
      + t12.root.exp_repet0.projection_HIPswitch.main_eigvecs_final[:,0].real.reshape(128, 128)[32:96, 32:96])
grid(False)
colorbar()

In [14]:
figure()
plot(N.log10(-t7.root.exp_repet0.projection_HIPswitch.loops.cols.TP_least_ev[:]))

In [15]:
figure()
plot(N.log10(t7.root.exp_repet0.projection_HIPswitch.loops.cols.TP_dist_L2[:-1] - t7.root.exp_repet0.projection_HIPswitch.loops.cols.TP_dist_L2[-1]))

In [16]:
figure()
plot((t7.root.exp_repet0.projection_HIPswitch.loops.cols.TP_dist_L2[10:-1]))

In [17]:
r7 = EG.retrieve_main('clean_progs/Jonas_experiment_7_qubits/vignette_7_qubits_1e7.h5')

In [89]:
fig, (ax7, ax8, ax9, ax10, ax12) = subplots(ncols=5)
ims = []
for t, ax in [(t7, ax7), (t8, ax8), (t9, ax9), (t10, ax10), (t12, ax12)]:
    ims.append(ax.imshow(v1[t].real))
    ax.grid(False)
    
clims = [im.get_clim() for im in ims[-1:]]
vmin = min([clim[0] for clim in clims])
vmax = max([clim[1] for clim in clims])
for im in ims:
    im.set_clim(vmin=vmin,vmax=vmax)    

colorbar(ims[0], ax = (ax7, ax8, ax9, ax10, ax12))    

In [183]:
fig, axes  = subplots(nrows=2, ncols=5, dpi=6 * (128 - 2 * 36))
ax07, ax08, ax09, ax010, ax012 = axes[0]
ax7, ax8, ax9, ax10, ax12 = axes[1]
ims = []
for t, ax in [(t7, ax7), (t8, ax8), (t9, ax9), (t10, ax10), (t12, ax12)]:
    ims.append(ax.imshow(v2[t].imag[36:-36, 36:-36], cmap='inferno'))
    ax.grid(False)
    ax.tick_params(left=False, bottom=False, labelleft=False, labelbottom=False)

    
clims = [im.get_clim() for im in ims[-1:]]
vmin = min([clim[0] for clim in clims])
vmax = max([clim[1] for clim in clims])
for im in ims:
    im.set_clim(vmin=vmin,vmax=vmax)    

ims = []
for t, ax in [(t7, ax07), (t8, ax08), (t9, ax09), (t10, ax010), (t12, ax012)]:
    ims.append(ax.imshow(v1[t].real[36:-36, 36:-36], cmap='inferno'))
    ax.grid(False)
    ax.tick_params(left=False, bottom=False, labelleft=False, labelbottom=False)

    
clims = [im.get_clim() for im in ims[-1:]]
vmin = min([clim[0] for clim in clims])
vmax = max([clim[1] for clim in clims])
for im in ims:
    im.set_clim(vmin=vmin,vmax=vmax)    
subplots_adjust(wspace=.02, hspace=-0.48)
#colorbar(ims[0], ax = (ax7, ax8, ax9, ax10, ax12), shrink=.3)    

In [212]:
figure()
c1 = tolcolors_med_contrast['db']
c2 = tolcolors_med_contrast['dy']
c3 = tolcolors_med_contrast['dr']
x = [1e7, 1e8, 1e9, 1e10, 1e12]
plot(x,[H.end.cols.final_fidelity[:] for H in (H7, H8, H9, H10, H12)], label='fidelity', color = c1)
plot(x,[H.end.cols.final_dist_L1 for H in (H7, H8, H9, H10, H12)], label='$L^1$ error', color = c2)
xscale('log')
ylim(0, 1)
axvline(18**7, color=c3, ls='--')
annotate('number of \nmeasurement \nsettings', (19**7, .3), color=c3)
annotate('> 0.998', (1e12, 1), xytext=(2e11, .93), color=c1)
annotate('< 0.006', (1e12, 0), xytext=(2e11, .04), color=c2)
legend()

In [208]:
labels = ['True', '$10^7$', '$10^8$', '$10^9$', '$10^{10}$', '$10^{12}$']
first_eigval = [.875]
first_eigval += [H.main_eigvals_final[1] for H in (H7, H8, H9, H10, H12)]
second_eigval = [.125]
second_eigval += [H.main_eigvals_final[0] for H in (H7, H8, H9, H10, H12)]
all_other_eigval = [0]
all_other_eigval += [ (1 - H.main_eigvals_final[:].sum()) for H in (H7, H8, H9, H10, H12)]

x = np.arange(6)  # the label locations
width = 0.25  # the width of the bars

fig, ax = plt.subplots()
rects1 = ax.bar(x - width, first_eigval, width, color=c1, label='First eigenvalue')
rects2 = ax.bar(x, second_eigval, width, color=c2, label='Second eigenvalue')
rects3 = ax.bar(x + width, all_other_eigval, width, color=c3, label='Sum of other eigenvalues')

axhline(.875, color=c1, ls=':')
axhline(.125, color=c2, ls=':')

ax.set_ylim(0,1)

# Add some text for labels, title and custom x-axis tick labels, etc.
#ax.set_ylabel('Scores')
#ax.set_title('Scores by group and gender')
ax.set_xticks(x)
ax.set_xticklabels(labels)
ax.legend()


In [188]:
first_eigval = [.875]
first_eigval += [H.main_eigvals_final[1] for H in (H7, H8, H9, H10, H12)]
second_eigval = [.125]
second_eigval += [H.main_eigvals_final[0] for H in (H7, H8, H9, H10, H12)]
all_other_eigval = [0]
all_other_eigval += [ (1 - H.main_eigvals_final[:].sum()) for H in (H7, H8, H9, H10, H12)]
first_eigval, second_eigval, all_other_eigval

([0.875,
  0.8232094726818122,
  0.7945447675866234,
  0.8525585857402327,
  0.8636790471100192,
  0.8737196369445372],
 [0.125,
  0.04265898540287687,
  0.0798535435184852,
  0.10905582961028872,
  0.11734789007458139,
  0.12437797050835624],
 [0,
  0.13413154191531096,
  0.12560168889489143,
  0.03838558464947861,
  0.018973062815399455,
  0.0019023925471065573])

In [177]:
H12.end.cols.final_dist_L1[:], H12.end.cols.TPfinal_dist_L1[:]

(array([0.00536477]), array([0.00452471]))

In [19]:
t7.root.exp_repet0.projection_HIPswitch.active_w[:]

[array([2], dtype=int32),
 array([2, 3], dtype=int32),
 array([2, 4], dtype=int32),
 array([2, 5], dtype=int32),
 array([2, 5, 6], dtype=int32),
 array([2, 5, 6, 7], dtype=int32),
 array([2, 5, 6, 7, 8], dtype=int32),
 array([2, 5, 7, 9], dtype=int32),
 array([ 2,  5,  7,  9, 10], dtype=int32),
 array([ 2,  5,  7, 10, 11], dtype=int32),
 array([ 2,  5,  7, 10, 11, 12], dtype=int32),
 array([ 2,  5,  7, 10, 11, 12, 13], dtype=int32),
 array([ 2,  5,  7, 10, 11, 12, 13, 14], dtype=int32),
 array([ 2,  5,  7, 10, 11, 12, 13, 14, 15], dtype=int32),
 array([ 2,  5,  7, 10, 12, 13, 14, 15, 16], dtype=int32),
 array([ 2,  5,  7, 10, 12, 13, 14, 15, 16, 17], dtype=int32),
 array([ 2,  5,  7, 10, 12, 13, 14, 15, 16, 17, 18], dtype=int32),
 array([ 2,  5,  7, 10, 12, 13, 14, 15, 16, 17, 18, 19], dtype=int32),
 array([ 5,  7, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20], dtype=int32),
 array([33], dtype=int32),
 array([33, 34], dtype=int32),
 array([33, 35], dtype=int32),
 array([33, 36], dtype=int32)

In [215]:
mpl.__version__

'3.4.1'

In [ ]:
GridSpec

In [8]:
import cmath
def align(ref_vec, test_vec):
    phi = cmath.phase(N.vdot(ref_vec, test_vec))
    return test_vec * exp(- phi * 1j)

In [31]:
v1r, v2i = {}, {}
for t in [t7, t8, t9, t10, t12]:
    v1r[t] = align(t.root.main_eigvecs_true[:,1], t.root.exp_repet0.projection_HIPswitch.main_eigvecs_final[:,1]).real.reshape(128, 128)
    v2i[t] = align(t.root.main_eigvecs_true[:,0], t.root.exp_repet0.projection_HIPswitch.main_eigvecs_final[:,0]).imag.reshape(128, 128)

In [32]:
v1i, v2r = {}, {}
for t in [t7, t8, t9, t10, t12]:
    v1i[t] = align(t.root.main_eigvecs_true[:,1], t.root.exp_repet0.projection_HIPswitch.main_eigvecs_final[:,1]).imag.reshape(128, 128)
    v2r[t] = align(t.root.main_eigvecs_true[:,0], t.root.exp_repet0.projection_HIPswitch.main_eigvecs_final[:,0]).real.reshape(128, 128)

In [16]:
figure()
imshow(v1r[t7])
show()

In [21]:
ioff()
fig = figure(figsize=(12,9), dpi = 6 * (128 - 2 * 36))
# If you want to see in the notebook or around, change to:
# ion()
#fig = figure(figsize=(12,9), dpi = 2 * (128 - 2 * 36))

gs0 = GridSpec(1, 2, top=.92, bottom=.5)
gs1 = GridSpec(2, 5, top=.5)

ax_loss = fig.add_subplot(gs0[0])

c1 = tolcolors_med_contrast['db']
c2 = tolcolors_med_contrast['dy']
c3 = tolcolors_med_contrast['dr']
x = [1e7, 1e8, 1e9, 1e10, 1e12]
ax_loss.plot(x,[H.end.cols.final_fidelity[:] for H in (H7, H8, H9, H10, H12)], label='fidelity', color = c1)
ax_loss.plot(x,[H.end.cols.final_dist_L1 for H in (H7, H8, H9, H10, H12)], label='$L^1$ error', color = c2)
ax_loss.set_xscale('log')
ax_loss.set_ylim(0)
ax_loss.axvline(18**7, color=c3, ls='--')
ax_loss.annotate('number of \nmeasurement \nsettings', (19**7, .3), color=c3)
ax_loss.annotate('> 0.998', (1e12, 1), xytext=(2e11, .93), color=c1)
ax_loss.annotate('< 0.006', (1e12, 0), xytext=(2e11, .04), color=c2)
ax_loss.legend(loc='lower left')

ax_values = fig.add_subplot(gs0[1])
labels = ['True', '$10^7$', '$10^8$', '$10^9$', '$10^{10}$', '$10^{12}$']
first_eigval = [.875]
first_eigval += [H.main_eigvals_final[1] for H in (H7, H8, H9, H10, H12)]
second_eigval = [.125]
second_eigval += [H.main_eigvals_final[0] for H in (H7, H8, H9, H10, H12)]
all_other_eigval = [0]
all_other_eigval += [ (1 - H.main_eigvals_final[:].sum()) for H in (H7, H8, H9, H10, H12)]

x = np.arange(6)  # the label locations
width = 0.25  # the width of the bars

rects1 = ax_values.bar(x - width, first_eigval, width, color=c1, label='First eigenvalue')
rects2 = ax_values.bar(x, second_eigval, width, color=c2, label='Second eigenvalue')
rects3 = ax_values.bar(x + width, all_other_eigval, width, color=c3, label='Sum of other eigenvalues')

ax_values.axhline(.875, color=c1, ls=':')
ax_values.axhline(.125, color=c2, ls=':')

ax_values.set_ylim(0,1)

# Add some text for labels, title and custom x-axis tick labels, etc.
#ax.set_ylabel('Scores')
#ax.set_title('Scores by group and gender')
ax_values.set_xticks(x)
ax_values.set_xticklabels(labels)
ax_values.legend()


axB = {}
for i in range(2):
    for j in range(5):
        axB[i,j] = fig.add_subplot(gs1[i,j])

ts = [t7, t8, t9, t10, t12]
vs = [v1r, v2i]
for i, v in enumerate(vs):
    ims = []
    for j, t in enumerate(ts):        
        ims.append(axB[i,j].imshow(v[t][36:-36, 36:-36], cmap='inferno'))
        axB[i,j].grid(False)
        axB[i,j].tick_params(left=False, bottom=False, labelleft=False, labelbottom=False)

    clims = [im.get_clim() for im in ims[-1:]]
    vmin = min([clim[0] for clim in clims])
    vmax = max([clim[1] for clim in clims])    
    for im in ims:
        im.set_clim(vmin=vmin,vmax=vmax)    

        
        
#subplots_adjust(wspace=.02, hspace=-0.3)
#colorbar(ims[0], ax = (ax7, ax8, ax9, ax10, ax12), shrink=.3)    

In [22]:
axB[0,0].set_ylabel('First eigenvector')
axB[1,0].set_ylabel('Second eigenvector')
axB[1,0].set_xlabel('$10^7$ samples')
axB[1,1].set_xlabel('$10^8$ samples')
axB[1,2].set_xlabel('$10^9$ samples')
axB[1,3].set_xlabel('$10^{10}$ samples')
axB[1,4].set_xlabel('$10^{12}$ samples')
ax_values.set_xlabel('Sample size')
ax_loss.set_xlabel('Sample size')

fig.suptitle('Full channel tomography of a noisy (2-rank) QFT on 7 qubits with Pauli measurements', 
             fontsize='large', fontweight='bold', x=.52)

gs0.bottom = .59
gs0.left=.1
gs0.right=.95
gs0.top=.93
gs0.update()

gs1.left=.08
gs1.right=.95
gs1.wspace = 0.02
gs1.hspace = .02
gs1.bottom = .05
gs1.top = .51
gs1.update()

In [23]:
fig.savefig('vignette.png')
ion()

In [24]:
ioff()
fig.savefig('vignette.pdf')
ion()

In [36]:
fig, axB = subplots(4, 5, figsize=(12,9), dpi = 2 * (128 - 2 * 36))


ts = [t7, t8, t9, t10, t12]
vs = [v1r, v1i, v2r, v2i]
for i, v in enumerate(vs):
    ims = []
    for j, t in enumerate(ts):        
        ims.append(axB[i,j].imshow(v[t][36:-36, 36:-36], cmap='inferno'))
        axB[i,j].grid(False)
        axB[i,j].tick_params(left=False, bottom=False, labelleft=False, labelbottom=False)

    clims = [im.get_clim() for im in ims[-1:]]
    vmin = min([clim[0] for clim in clims])
    vmax = max([clim[1] for clim in clims])    
    for im in ims:
        im.set_clim(vmin=vmin,vmax=vmax)    

In [37]:
subplots_adjust(wspace=.02, hspace=.02)

In [ ]:
gs[1].subgridspec

In [287]:
subplots_adjust?

In [270]:
GridSpec?

In [302]:
superfig.subplots?

In [286]:
superfig.suptitle('Full channel tomography of a noisy (2-rank) QFT on 7 qubits with Pauli measurements', fontsize='x-large', y=.995)


Text(0.5, 0.995, 'Full channel tomography of a noisy (2-rank) QFT on 7 qubits with Pauli measurements')

In [291]:
GridSpec?

In [292]:
mpl.gridspec.GridSpecFromSubplotSpec?

In [293]:
superfig.add_subplot?

In [305]:
for i, con in enumerate([3, 1e2, 'a']):
    print((i, con))

(0, 3)
(1, 100.0)
(2, 'a')


In [308]:
d = {}
d[1,4]  = 2

In [309]:
d[1,4]

2